version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=toor
    ports:
      # AMQP protocol port
      - '5672:5672'
    volumes:
      - ./docker/rabbitmq/:/etc/rabbitmq/
    networks:
      protected:
        ipv4_address: 10.100.0.10

  cleverbot:
    build:
      context: .
      dockerfile: cleverbot.Dockerfile
    container_name: 'cleverbot'
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=10.100.0.10
      - RABBIT_PORT=5672
      - RABBIT_USER=admin
      - RABBIT_PASW=toor
    networks:
      protected:
        ipv4_address: 10.100.0.20

networks:
  protected:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.10/24

